name: CI
on: [push]
jobs:
  FrontDeploy:
    name: FrontDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: deploy to Firebase Hosting
        shell: bash
        run: npm run channel-deploy $(echo ${GITHUB_REF#refs/heads/}) --token=${{ secrets.FIREBASE_TOKEN }}
